services:
  java-lab:
    build: .
    container_name: java-lab
    volumes:
      - ./sripts:/lab/scripts
      - ./src:/lab/src
      - ./bin:/lab/bin
    working_dir: /lab
    command: tail -f /dev/null
